# Generated by Django 4.1.7 on 2023-08-01 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_6', '0003_remove_gamemodel_eu_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='eu_sales',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='global_sales',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='jp_sales',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='na_sales',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='other_sales',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='year',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
